export const departments = [
  {
    id: "1",
    name: "Web Development",
    icon: "Code",
    description: "Learn to build modern web applications",
    color: "#3b82f6",
    courses: ["1", "2", "3"],
  },
  {
    id: "2",
    name: "Data Science",
    icon: "Database",
    description: "Master data analysis and visualization",
    color: "#10b981",
    courses: ["4", "5"],
  },
  {
    id: "3",
    name: "Mobile Development",
    icon: "Smartphone",
    description: "Build apps for iOS and Android",
    color: "#f59e0b",
    courses: ["6", "7"],
  },
  {
    id: "4",
    name: "DevOps & Cloud",
    icon: "Cloud",
    description: "Deploy and manage applications at scale",
    color: "#8b5cf6",
    courses: ["8", "9"],
  },
];

export const courses = [
  {
    id: "1",
    departmentId: "1",
    name: "React Fundamentals",
    icon: "React",
    difficulty: "Beginner",
    tools: ["JavaScript", "React", "CSS"],
    projects: ["1", "2"],
  },
  {
    id: "2",
    departmentId: "1",
    name: "Advanced TypeScript",
    icon: "TypeScript",
    difficulty: "Advanced",
    tools: ["TypeScript", "Node.js"],
    projects: ["3", "4"],
  },
  {
    id: "3",
    departmentId: "1",
    name: "Next.js Full Stack",
    icon: "Zap",
    difficulty: "Intermediate",
    tools: ["Next.js", "Node.js", "PostgreSQL"],
    projects: ["5", "6"],
  },
  {
    id: "4",
    departmentId: "2",
    name: "Python for Data",
    icon: "PieChart",
    difficulty: "Beginner",
    tools: ["Python", "Pandas", "NumPy"],
    projects: ["7", "8"],
  },
  {
    id: "5",
    departmentId: "2",
    name: "Machine Learning Basics",
    icon: "Brain",
    difficulty: "Intermediate",
    tools: ["Python", "TensorFlow", "Scikit-learn"],
    projects: ["9", "10"],
  },
  {
    id: "6",
    departmentId: "3",
    name: "React Native",
    icon: "Smartphone",
    difficulty: "Intermediate",
    tools: ["React Native", "JavaScript"],
    projects: ["11", "12"],
  },
  {
    id: "7",
    departmentId: "3",
    name: "Flutter Basics",
    icon: "Wind",
    difficulty: "Beginner",
    tools: ["Flutter", "Dart"],
    projects: ["13"],
  },
  {
    id: "8",
    departmentId: "4",
    name: "Docker & Kubernetes",
    icon: "Container",
    difficulty: "Advanced",
    tools: ["Docker", "Kubernetes"],
    projects: ["14", "15"],
  },
  {
    id: "9",
    departmentId: "4",
    name: "AWS Solutions",
    icon: "Cloud",
    difficulty: "Intermediate",
    tools: ["AWS", "Lambda", "RDS"],
    projects: ["16"],
  },
];

export const projects = [
  {
    id: "1",
    courseId: "1",
    title: "Build a Todo App",
    description: "Create a fully functional todo application with React",
    difficulty: "Beginner",
    price: 29,
    tools: ["React", "JavaScript", "CSS"],
    duration: "2 weeks",
    learningOutcomes: [
      "Understand React components and hooks",
      "Master state management",
      "Build interactive UIs",
    ],
    locked: true,
  },
  {
    id: "2",
    courseId: "1",
    title: "E-commerce Product Page",
    description: "Design and build a modern e-commerce product page",
    difficulty: "Intermediate",
    price: 49,
    tools: ["React", "TypeScript", "Tailwind CSS"],
    duration: "3 weeks",
    learningOutcomes: [
      "Build reusable components",
      "Handle complex state",
      "Optimize for performance",
    ],
    locked: true,
  },
  {
    id: "3",
    courseId: "2",
    title: "TypeScript Utilities Library",
    description: "Build a comprehensive utilities library with TypeScript",
    difficulty: "Advanced",
    price: 79,
    tools: ["TypeScript", "Jest", "npm"],
    duration: "4 weeks",
    learningOutcomes: [
      "Master TypeScript generics",
      "Write type-safe code",
      "Create reusable libraries",
    ],
    locked: true,
  },
  {
    id: "4",
    courseId: "2",
    title: "RESTful API with Node.js",
    description: "Build a scalable REST API using Node.js and Express",
    difficulty: "Intermediate",
    price: 59,
    tools: ["Node.js", "Express", "MongoDB"],
    duration: "3 weeks",
    learningOutcomes: [
      "Design API architecture",
      "Handle authentication",
      "Optimize database queries",
    ],
    locked: true,
  },
  {
    id: "5",
    courseId: "3",
    title: "Full Stack Blog Platform",
    description: "Create a complete blog platform with Next.js",
    difficulty: "Intermediate",
    price: 69,
    tools: ["Next.js", "PostgreSQL", "Tailwind CSS"],
    duration: "4 weeks",
    learningOutcomes: [
      "Build full stack applications",
      "Manage databases",
      "Deploy to production",
    ],
    locked: true,
  },
  {
    id: "6",
    courseId: "3",
    title: "Real-time Chat Application",
    description: "Build a real-time chat app with WebSockets",
    difficulty: "Advanced",
    price: 89,
    tools: ["Next.js", "WebSockets", "Redis"],
    duration: "5 weeks",
    learningOutcomes: [
      "Implement real-time features",
      "Handle concurrent connections",
      "Scale applications",
    ],
    locked: true,
  },
  {
    id: "7",
    courseId: "4",
    title: "Data Analysis Project",
    description: "Analyze real-world datasets using Python",
    difficulty: "Beginner",
    price: 39,
    tools: ["Python", "Pandas", "Matplotlib"],
    duration: "2 weeks",
    learningOutcomes: [
      "Clean and prepare data",
      "Perform exploratory analysis",
      "Visualize results",
    ],
    locked: true,
  },
  {
    id: "8",
    courseId: "4",
    title: "Financial Data Analysis",
    description: "Analyze stock market data and build predictions",
    difficulty: "Intermediate",
    price: 59,
    tools: ["Python", "Pandas", "Scikit-learn"],
    duration: "3 weeks",
    learningOutcomes: [
      "Work with time-series data",
      "Build predictive models",
      "Create visualizations",
    ],
    locked: true,
  },
  {
    id: "9",
    courseId: "5",
    title: "Image Classification Model",
    description: "Build a neural network for image classification",
    difficulty: "Intermediate",
    price: 69,
    tools: ["Python", "TensorFlow", "OpenCV"],
    duration: "4 weeks",
    learningOutcomes: [
      "Understand neural networks",
      "Train deep learning models",
      "Evaluate model performance",
    ],
    locked: true,
  },
  {
    id: "10",
    courseId: "5",
    title: "NLP Chatbot Project",
    description: "Create an AI-powered chatbot using NLP",
    difficulty: "Advanced",
    price: 79,
    tools: ["Python", "TensorFlow", "NLTK"],
    duration: "4 weeks",
    learningOutcomes: [
      "Master NLP concepts",
      "Build language models",
      "Deploy AI applications",
    ],
    locked: true,
  },
  {
    id: "11",
    courseId: "6",
    title: "React Native App",
    description: "Build a cross-platform mobile app",
    difficulty: "Intermediate",
    price: 59,
    tools: ["React Native", "JavaScript"],
    duration: "3 weeks",
    learningOutcomes: [
      "Build mobile apps",
      "Share code between platforms",
      "Access native APIs",
    ],
    locked: true,
  },
  {
    id: "12",
    courseId: "6",
    title: "Social Media App",
    description: "Build a feature-rich social app with React Native",
    difficulty: "Advanced",
    price: 79,
    tools: ["React Native", "Firebase", "Redux"],
    duration: "5 weeks",
    learningOutcomes: [
      "Build complex UIs",
      "Implement real-time features",
      "Optimize performance",
    ],
    locked: true,
  },
  {
    id: "13",
    courseId: "7",
    title: "Flutter Weather App",
    description: "Build a beautiful weather application",
    difficulty: "Beginner",
    price: 39,
    tools: ["Flutter", "Dart", "API"],
    duration: "2 weeks",
    learningOutcomes: [
      "Learn Flutter basics",
      "Work with APIs",
      "Create beautiful UIs",
    ],
    locked: true,
  },
  {
    id: "14",
    courseId: "8",
    title: "Containerize Applications",
    description: "Master Docker for application deployment",
    difficulty: "Advanced",
    price: 79,
    tools: ["Docker", "Container"],
    duration: "3 weeks",
    learningOutcomes: [
      "Create Docker images",
      "Manage containers",
      "Deploy to production",
    ],
    locked: true,
  },
  {
    id: "15",
    courseId: "8",
    title: "Orchestrate with Kubernetes",
    description: "Master Kubernetes cluster management",
    difficulty: "Advanced",
    price: 89,
    tools: ["Kubernetes", "Docker"],
    duration: "4 weeks",
    learningOutcomes: [
      "Deploy to Kubernetes",
      "Manage clusters",
      "Scale applications",
    ],
    locked: true,
  },
  {
    id: "16",
    courseId: "9",
    title: "AWS Architecture Design",
    description: "Design scalable cloud solutions on AWS",
    difficulty: "Intermediate",
    price: 69,
    tools: ["AWS", "Lambda", "RDS"],
    duration: "3 weeks",
    learningOutcomes: [
      "Design cloud architecture",
      "Use AWS services",
      "Optimize costs",
    ],
    locked: true,
  },
];
